name: Sync release/b branch to master

on:
   pull_request:
      types: colsed
      branches: 
         - "release/b"
   push:
    branches:
      - "release/b"
jobs:
  merge-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'master'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
