name: Merge release/a to release/b
on: 
  push:
     branches: 
        - "release/a"
jobs:
  build:
    name: Gitflow
    runs-on: ubuntu-16.04
    steps:
    - uses: vijaymajagaonkar/gitflow-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        release: release/a
        master: release/b
        label: gitflow
        auto-merge: true 
        require-merge: true 
