name: Merge release/b branch to master
on: 
  workflow_run:
    workflows: ["Merge release/a to release/b"]
    branches: 
      - "release/a"
    types:
      - completed
  push:
     branches: 
        - "release/b"
jobs:
  build:
    name: Gitflow
    runs-on: ubuntu-16.04
    steps:
    - uses: Logerfo/gitflow-action@0.0.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        release: release/b
        master: master
        label: gitflow
        auto-merge: true 
        require-merge: true 
