name: Sync to next release branch
# on:
#   push:
#     branches:
#       - 'release/b'

# jobs:
#   merge-branch:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master

#       - name: Merge release/b -> master
#         uses: devmasx/merge-branch@v1.3.0
#         with:
#           type: now
#           label_name: 'merged in master'
#           target_branch: master
#           github_token: ${{ github.token }}

on:
  push:
    branches:
      - "release/b"
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'master'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'

