name: Sync to next release branch
on:
  push:
    branches:
      - 'release/a'

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@'release/b'

      - name: Merge staging -> uat
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          label_name: 'meged in release/b'
          target_branch: release/b
          github_token: ${{ github.token }}
